version: '2'
services:
    testjh2-app:
        image: testjh2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testjh2-postgresql:5432/testjh2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testjh2-postgresql:
        extends:
            file: postgresql.yml
            service: testjh2-postgresql
